resolver: lts-11.13

packages:
- .
- location:
    git: https://github.com/bitemyapp/esqueleto.git
    commit: 632f4408df05501b02d3e2f951bfdd335ea515ba
  extra-dep: true
# - location:
#     git:
allow-newer: true

extra-deps:
  - time-1.9.1
